# src/api/main.py
# ChronoOpt FastAPI application.
#
# Run from project root:
#   uvicorn src.api.main:app --reload
#
# Interactive API docs (auto-generated by FastAPI):
#   http://localhost:8000/docs


from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
import os

from src.api import inference, database
from src.api.models import (
    RecommendationResponse,
    OutcomeLog,
    HistoryEntry,
    HealthResponse,
)


# ---------------------------------------------------------------------------
# Lifespan: runs startup and shutdown logic for the app process.
# This is the correct FastAPI pattern for expensive one-time setup like
# loading ML models — avoids the deprecated @app.on_event approach.
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    # STARTUP
    print("[startup] Initialising database...")
    database.init_db()

    print("[startup] Loading ML models...")
    inference.load_all_models()

    print("[startup] ChronoOpt API ready.")
    yield

    # SHUTDOWN (nothing to clean up — model memory released by process exit)
    print("[shutdown] Goodbye.")


# ---------------------------------------------------------------------------
# App definition
# ---------------------------------------------------------------------------

app = FastAPI(
    title="ChronoOpt API",
    description=(
        "Personal circadian rhythm optimisation system. "
        "Ingests Garmin biometric data, trains an LSTM to predict next-day physiology, "
        "and uses a PPO RL agent to recommend optimal daily behaviours."
    ),
    version="0.1.0",
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health", response_model=HealthResponse, tags=["System"])
def health():
    """
    Operational status of all system components.
    Useful for confirming models loaded correctly before fetching a recommendation.
    """
    status = inference.is_ready()
    all_ok = status["lstm_loaded"] and status["processor_fitted"]

    return HealthResponse(
        status="ok" if all_ok else "degraded",
        lstm_loaded=status["lstm_loaded"],
        policy_loaded=status["policy_loaded"],
        processor_fitted=status["processor_fitted"],
        last_garmin_fetch_date=status["last_garmin_fetch_date"],
        garmin_days_available=status["garmin_days_available"],
        policy_path=str(inference._policy_source),
        message=(
            "All systems operational."
            if all_ok
            else "Some components failed to load — check startup logs."
        ),
    )


@app.get("/recommend", response_model=RecommendationResponse, tags=["Recommendations"])
def recommend(background_tasks: BackgroundTasks, refresh: bool = False):
    """
    Generate today's personalised daily recommendation.

    Fetches your last 10 days of Garmin data from local cache, runs the
    trained PPO policy on that real state, and returns the recommended
    steps, activity, bed time, and wake time — along with the predicted
    sleep score for that recommendation vs repeating yesterday's behaviour.

    The recommendation is cached after the first call of the day — subsequent
    calls return the stored result instantly without re-running inference.
    Pass `?refresh=true` to force re-computation (e.g. after new Garmin data).

    The recommendation is automatically persisted to the local SQLite
    database in the background so it appears in /history.
    """
    from datetime import date as _date

    today = _date.today().isoformat()

    # Return cached recommendation if it exists and refresh not requested
    if not refresh:
        cached = database.get_recommendation_for_date(today)
        if cached:
            return RecommendationResponse(**cached)

    try:
        result = inference.get_recommendation()
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Inference failed: {e}")

    background_tasks.add_task(database.upsert_recommendation, result)

    return RecommendationResponse(**result)


@app.post("/log-outcome", tags=["Tracking"])
def log_outcome(outcome: OutcomeLog):
    """
    Log what you actually did today.

    Accepts partial data — you don't need to fill every field. If an actual
    sleep score is provided, the system computes the calibration error
    (predicted vs actual) and logs it for model performance tracking.

    Over time this data feeds the online personalisation loop: the more
    real outcomes you log, the more the policy adapts to your specific
    physiology.
    """
    try:
        database.upsert_outcome(outcome.model_dump())
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to log outcome: {e}")

    return {"status": "logged", "date": outcome.date}


@app.get("/history", response_model=list[HistoryEntry], tags=["Tracking"])
def history(days: int = 30):
    """
    Returns the last N days of recommendations alongside logged actual outcomes.

    The `score_delta` field (actual minus predicted) is the key metric for
    evaluating model calibration — a well-calibrated model will have deltas
    close to zero on average.
    """
    if days < 1 or days > 365:
        raise HTTPException(status_code=400, detail="days must be between 1 and 365")

    rows = database.get_history(limit=days)
    return [HistoryEntry(**row) for row in rows]


# ---------------------------------------------------------------------------
# Static file serving — the dashboard lives at /
# ---------------------------------------------------------------------------

STATIC_DIR = os.path.join(os.path.dirname(__file__), "static")

if os.path.isdir(STATIC_DIR):
    app.mount("/", StaticFiles(directory=STATIC_DIR, html=True), name="static")
else:
    @app.get("/", tags=["System"])
    def root():
        """Dashboard not yet built — use /docs to interact with the API."""
        return {
            "message": "ChronoOpt API is running.",
            "docs": "/docs",
            "health": "/health",
            "recommend": "/recommend",
        }
