# src/api/main.py
# ChronoOpt FastAPI application.
#
# Run from project root:
#   uvicorn src.api.main:app --reload
#
# Interactive API docs (auto-generated by FastAPI):
#   http://localhost:8000/docs


from contextlib import asynccontextmanager
from datetime import date

from fastapi import Depends, FastAPI, HTTPException, BackgroundTasks, Request
from fastapi.staticfiles import StaticFiles
import os

from src.api import inference, database
from src.api.inference import ModelBundle
from src.api.models import (
    RecommendationResponse,
    OutcomeLog,
    HistoryEntry,
    HealthResponse,
)
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from src.api.online_loop import register_nightly_job
from src.api.online_loop import run_nightly_loop

# ---------------------------------------------------------------------------
# Lifespan
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    print("[startup] Initialising database...")
    database.init_db()

    print("[startup] Loading ML models...")
    app.state.models = inference.load_all_models()  # stored on app.state, not a global

    scheduler = AsyncIOScheduler()
    register_nightly_job(scheduler,app.state)
    scheduler.start()
    app.state.scheduler = scheduler
    print("[startup] ChronoOpt API ready.")
    yield
    app.state.scheduler.shutdown()
    print("[shutdown] Goodbye.")


# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(
    title="ChronoOpt API",
    description=(
        "Personal circadian rhythm optimisation system. "
        "Ingests Garmin biometric data, trains an LSTM to predict next-day physiology, "
        "and uses a PPO RL agent to recommend optimal daily behaviours."
    ),
    version="0.1.0",
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# Dependency
#
# Endpoints that need ML models declare: models: ModelBundle = Depends(get_ml_models)
# In tests, swap this out cleanly with:
#   app.dependency_overrides[get_ml_models] = lambda: mock_bundle
# ---------------------------------------------------------------------------

def get_ml_models(request: Request) -> ModelBundle:
    """Retrieves the loaded ModelBundle from app.state."""
    return request.app.state.models


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health", response_model=HealthResponse, tags=["System"])
def health(models: ModelBundle = Depends(get_ml_models)):
    """
    Operational status of all system components.
    Check this first to confirm models loaded correctly before running inference.
    """
    ok = models.is_healthy
    last_date = database.get_last_recommendation_date()
    return HealthResponse(
        status="ok" if ok else "degraded",
        lstm_loaded=models.lstm is not None,
        policy_loaded=models.policy is not None,
        processor_fitted=models.processor._is_scaler_fitted,
        last_garmin_fetch_date=last_date,   # populated after first /recommend call
        garmin_days_available=10 if last_date else 0,
        policy_path=models.policy_source,
        message="All systems operational." if ok else "Some components failed — check startup logs.",
    )


@app.get("/recommend", response_model=RecommendationResponse, tags=["Recommendations"])
def recommend(
    background_tasks: BackgroundTasks,
    refresh: bool = False,
    models: ModelBundle = Depends(get_ml_models),
):
    """
    Generate today's personalised daily recommendation.

    Fetches your last 10 days of Garmin data from local cache, runs the
    trained PPO policy on that real state, and returns the recommended
    steps, activity, bed time, and wake time, alongside the predicted
    sleep score for the recommendation vs repeating yesterday's behaviour.

    Caching: the recommendation is computed once per day and stored in
    the local SQLite database. Subsequent calls return the cached result
    immediately. Pass `?refresh=true` to force re-computation (e.g. after
    new Garmin data arrives).
    """
    today = date.today().isoformat()

    if not refresh:
        cached = database.get_recommendation_for_date(today)
        if cached:
            return RecommendationResponse(**cached)

    try:
        result = inference.get_recommendation(models) 
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Inference failed: {e}")

    background_tasks.add_task(database.upsert_recommendation, result)
    return RecommendationResponse(**result)


@app.post("/log-outcome", tags=["Tracking"])
def log_outcome(outcome: OutcomeLog):
    """
    Log what you actually did today.

    All fields are optional — log what you know. If you provide an actual
    sleep score, the system records the calibration error (predicted vs actual)
    in the model log, which feeds the online personalisation loop over time.
    """
    try:
        database.upsert_outcome(outcome.model_dump())
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to log outcome: {e}")

    return {"status": "logged", "date": outcome.date}


@app.get("/history", response_model=list[HistoryEntry], tags=["Tracking"])
def history(days: int = 30):
    """
    Last N days of recommendations alongside logged actual outcomes.

    The `score_delta` field (actual − predicted) tracks model calibration
    over time — a well-calibrated model should have deltas close to zero
    on average.
    """
    if not 1 <= days <= 365:
        raise HTTPException(status_code=400, detail="days must be between 1 and 365")

    rows = database.get_history(limit=days)
    return [HistoryEntry(**row) for row in rows]

@app.post("/loop/run", tags=["System"])
async def trigger_loop():
    """Manually trigger the nightly loop."""
    return await run_nightly_loop(app.state)

# ---------------------------------------------------------------------------
# Static files — dashboard at /
# ---------------------------------------------------------------------------

STATIC_DIR = os.path.join(os.path.dirname(__file__), "static")

if os.path.isdir(STATIC_DIR):
    app.mount("/", StaticFiles(directory=STATIC_DIR, html=True), name="static")
else:
    @app.get("/", tags=["System"])
    def root():
        """Dashboard not built yet — use /docs to interact with the API."""
        return {
            "message": "ChronoOpt API is running.",
            "docs": "/docs",
            "health": "/health",
            "recommend": "/recommend",
        }